/**
 * Catálogo de la biblioteca física del usuario, transcrito de su listado.
 * Formato: [título, autor, categoría, año | null]
 */

export const CATALOG = [
  /* ── 🏛️ Novela Histórica y de Época ──────────────────────────────── */
  ["Imprimatur", "Monaldi & Sorti", "Novela Histórica / Intriga", 2002],
  ["Gunter de Amalfi: Caballero templario", "Franco Cuomo", "Novela Histórica", 1997],
  ["Las tumbas del mañana", "Anne Perry", "Novela Histórica / Policial", 2001],
  ["El caballero del Temple", "José Luis Corral", "Novela Histórica", 2006],
  ["El Rey Bastardo", "Jean Plaidy", "Novela Histórica", 1979],
  ["Sinuhé, el egipcio", "Mika Waltari", "Ficción Histórica Clásica", 1945],
  ["Los pilares de la Tierra", "Ken Follett", "Novela Histórica / Drama", 1989],
  ["La reina descalza", "Ildefonso Falcones", "Novela Histórica", 2013],
  ["Río de pasiones", "Kathleen Woodiwiss", "Novela Romántica Histórica", 1980],
  ["La enfermera de Auschwitz", "Anna Stuart", "Ficción Histórica", 2021],
  ["El médico", "Noah Gordon", "Novela Histórica", 1986],
  ["El chamán", "Noah Gordon", "Novela Histórica", 1992],
  ["La doctora Cole", "Noah Gordon", "Novela Histórica", 1995],
  ["El diamante de Jerusalén", "Noah Gordon", "Novela Histórica / Intriga", 1979],
  ["El faraón negro", "Christian Jacq", "Novela Histórica", 1997],
  ["El Cid (I)", "José Luis Corral", "Novela Histórica", 2007],
  ["El Cid (II)", "José Luis Corral", "Novela Histórica", 2007],
  ["¡A los leones!", "Lindsey Davis", "Novela Histórica / Policial", 1998],
  ["Alejandro", "Gisbert Haefs", "Novela Histórica", 1990],
  ["La torre de los alquimistas", "Peter G. Bartschat", "Novela Histórica", 1998],
  ["Aníbal", "Gisbert Haefs", "Novela Histórica", 1989],

  /* ── 📿 Biblioteca Christian Jacq ─────────────────────────────────── */
  ["Ramsés. La batalla de Kadesh", "Christian Jacq", "Novela Histórica (Egipto)", 1996],
  ["Nefertiti y Akenatón", "Christian Jacq", "Ensayo / Novela Histórica", 1990],
  ["Ramsés. Bajo la acacia de occidente", "Christian Jacq", "Novela Histórica (Egipto)", 1996],
  ["El egiptólogo", "Christian Jacq", "Novela Histórica", 1992],
  ["El iniciado", "Christian Jacq", "Novela Histórica", 1994],
  ["El origen de los dioses", "Christian Jacq", "Novela Histórica / Divulgación", 1992],
  ["El misterio de las catedrales", "Christian Jacq", "Ensayo Histórico", 1998],
  ["Ramsés. El templo de millones de años", "Christian Jacq", "Novela Histórica (Egipto)", 1995],
  ["Las egipcias", "Christian Jacq", "Ensayo / Novela Histórica", 1996],
  ["El templo del Rey Salomón", "Christian Jacq", "Novela Histórica", 1989],
  ["Ramsés. La dama de Abu Simbel", "Christian Jacq", "Novela Histórica (Egipto)", 1996],
  ["La reina Sol", "Christian Jacq", "Novela Histórica", 1998],
  ["El Valle de los Reyes", "Christian Jacq", "Ensayo / Novela Histórica", 1992],
  ["El Antiguo Egipto día a día", "Christian Jacq", "Historia / Divulgación", 2002],
  ["La piedra de luz 1. Nefer el silencioso", "Christian Jacq", "Novela Histórica", 2000],
  ["La piedra de luz 2. La mujer sabia", "Christian Jacq", "Novela Histórica", 2000],
  ["La pirámide asesinada", "Christian Jacq", "Novela Histórica / Misterio", 1993],
  ["El enigma de la piedra", "Christian Jacq", "Novela Histórica", 1993],
  ["Ramsés. El hijo de la luz", "Christian Jacq", "Novela Histórica (Egipto)", 1995],
  ["El Egipto de los grandes faraones", "Christian Jacq", "Historia / Divulgación", 1981],
  ["La sabiduría viva del Antiguo Egipto", "Christian Jacq", "Ensayo / Filosofía", 1998],
  ["La piedra de luz 3. Paneb el ardiente", "Christian Jacq", "Novela Histórica", 2000],
  ["La piedra de luz 4. Lugar de verdad", "Christian Jacq", "Novela Histórica", 2000],
  ["Las máximas de Ptahhotep", "Christian Jacq", "Ensayo / Filosofía", 2004],
  ["Ramsés: El hijo de la luz (Ed. amarilla)", "Christian Jacq", "Novela Histórica", 1995],
  ["La ley del desierto", "Christian Jacq", "Novela Histórica", 1993],
  ["La justicia del visir", "Christian Jacq", "Novela Histórica", 1994],

  /* ── 🕵️ Thriller, Misterio y Novela Negra ─────────────────────────── */
  ["El club Dante", "Matthew Pearl", "Thriller Histórico", 2003],
  ["La chica del tren", "Paula Hawkins", "Thriller Psicológico", 2015],
  ["El ocho", "Katherine Neville", "Thriller / Misterio", 1988],
  ["Falsa identidad", "David Morrell", "Thriller / Suspense", 1998],
  ["La chica del tambor", "John le Carré", "Thriller / Espionaje", 1983],
  ["El testamento de Judas", "Daniel Easterman", "Thriller / Misterio Religioso", 1992],
  ["Justicia corrupta", "Nancy Taylor Rosenberg", "Thriller Judicial", 1993],
  ["Mary Terror", "Robert R. McCammon", "Thriller / Suspense", 1990],
  ["Juegos sucios", "Michael Dibdin", "Novela Negra / Policial", 1999],
  ["La estación de los monzones", "Paul Mann", "Thriller / Misterio", 1992],
  ["Clockers", "Richard Price", "Novela Negra / Policial", 1992],
  ["El tercer gemelo", "Ken Follett", "Thriller Científico", 1996],
  ["Jurassic Park (Parque Jurásico)", "Michael Crichton", "Ciencia Ficción / Thriller", 1990],
  ["Chacal", "Frederick Forsyth", "Thriller de Espionaje", 1971],
  ["El jurado", "John Grisham", "Thriller Judicial", 1996],
  ["Huida al sur", "Robert R. McCammon", "Thriller / Aventura", 1987],
  ["El Gen", "Michael Cordy", "Thriller Científico", 1997],
  ["Jurado 224", "George Dawes Green", "Thriller Judicial", 1995],
  ["Asesinos sin rostro", "Henning Mankell", "Novela Negra / Policial", 1991],
  ["El silencio de la ciudad blanca", "Eva García Sáenz de Urturi", "Novela Negra / Thriller", 2016],
  ["Tokio blues (Norwegian Wood)", "Haruki Murakami", "Ficción / Drama Psicológico", 1987],
  ["Los crímenes de Anubis", "Paul Doherty", "Novela Policial Histórica", 1997],
  ["Memento de difuntos", "Andreu Martín", "Novela Negra / Misterio", 2007],

  /* ── 🩺 Colección Robin Cook ──────────────────────────────────────── */
  ["Como si fuera Dios", "Robin Cook", "Thriller Médico", 1982],
  ["Toxina", "Robin Cook", "Thriller Médico", 1998],
  ["Epidemia", "Robin Cook", "Thriller Médico", 1987],
  ["Vector", "Robin Cook", "Thriller Médico", 1999],
  ["Tratamiento letal", "Robin Cook", "Thriller Médico", 1993],
  ["La manipulación de las mentes", "Robin Cook", "Thriller Médico", 1979],
  ["Cromosoma 6", "Robin Cook", "Thriller Médico", 1997],
  ["Miedo mortal", "Robin Cook", "Thriller Médico", 1988],
  ["Invasión", "Robin Cook", "Ciencia Ficción / Thriller", 1997],
  ["Los archivos de Salem", "Robin Cook", "Thriller / Histórico", 1994],
  ["Contagio", "Robin Cook", "Thriller Médico", 1995],
  ["Intención criminal", "Robin Cook", "Thriller Médico", 1985],
  ["Ceguera asesina", "Robin Cook", "Thriller Médico", 1992],
  ["Signos vitales", "Robin Cook", "Thriller Médico", 1991],

  /* ── 🎈 Infantil y Juvenil ────────────────────────────────────────── */
  ["Pupi y la aventura de los cowboys", "María Menéndez-Ponte", "Literatura Infantil", 2005],
  ["Pupi y los fantasmas", "María Menéndez-Ponte", "Literatura Infantil", 2000],
  ["Pupi y el club de los dinosaurios", "María Menéndez-Ponte", "Literatura Infantil", 2002],
  ["Pupi y el cabeza hueca", "María Menéndez-Ponte", "Literatura Infantil", 2003],
  ["Un monstruo en el armario", "Carmen Vázquez-Vigo", "Literatura Infantil", 1989],
  ["Pupi y el Monstruo de la Vergüenza", "María Menéndez-Ponte", "Literatura Infantil", 2008],
  ["Pupi quiere ser futbolista", "María Menéndez-Ponte", "Literatura Infantil", 2006],
  ["Pupi va al hospital", "María Menéndez-Ponte", "Literatura Infantil", 2007],
  ["Pupi y Lila juegan al escondite", "María Menéndez-Ponte", "Literatura Infantil", 2009],
  ["Pupi y los verdorolos", "María Menéndez-Ponte", "Literatura Infantil", 2010],
  ["El cumpleaños de Pupi", "María Menéndez-Ponte", "Literatura Infantil", 2004],
  ["Diary of a Wimpy Kid: The Last Straw", "Jeff Kinney", "Novela Gráfica / Juvenil", 2009],
  ["Diario de Greg: La ley de Rodrick", "Jeff Kinney", "Novela Gráfica / Juvenil", 2008],
  ["Diario de Greg: Un pringao total", "Jeff Kinney", "Novela Gráfica / Juvenil", 2007],
  ["Viaje en el Tiempo 1", "Geronimo Stilton", "Literatura Infantil", 2002],
  ["Viaje en el Tiempo 2", "Geronimo Stilton", "Literatura Infantil", 2004],
  ["El reino perdido", "Geronimo Stilton", "Fantasía Infantil", 2009],
  ["Viaje en el Tiempo 4", "Geronimo Stilton", "Literatura Infantil", 2008],
  ["Viaje en el Tiempo 3", "Geronimo Stilton", "Literatura Infantil", 2006],
  ["El misterio de la muñeca desaparecida", "Tea Stilton", "Literatura Infantil", 2009],
  ["Princesa del desierto", "Tea Stilton", "Fantasía Infantil", 2011],
  ["Junie B. Jones tiene un hermano monísimo", "Barbara Park", "Literatura Infantil", 1997],
  ["Junie B. Jones y la fiesta de pijamas", "Barbara Park", "Literatura Infantil", 1998],
  ["Junie B. Jones y el diario de clase", "Barbara Park", "Literatura Infantil", 2001],
  ["Junie B. Jones monta el numerito", "Barbara Park", "Literatura Infantil", 2002],
  ["Quinto grado en Torres de Malory", "Enid Blyton", "Literatura Juvenil", 1950],
  ["Mi amigo Luki-live", "Christine Nöstlinger", "Literatura Juvenil", 1978],
  ["Olympia 3: Un corazón dividido", "Almudena Cid", "Literatura Juvenil / Deporte", 2015],
  ["Olympia y las auténticas deportistas", "Almudena Cid", "Literatura Juvenil / Deporte", 2017],
  ["El misterio de las letras perdidas", "Alicia Barberis", "Literatura Infantil", 2004],
  ["Soy Luna: El viaje comienza", "Varios (Disney)", "Juvenil / Serie", 2016],
  ["Sonríe aunque te cueste", "Ángela Mármol", "Juvenil / Autobiografía", 2019],
  ["La tinta de mis ojos", "Aitana Ocaña", "Arte / Juvenil", 2018],
  ["Los diamantes de Oberón", "Fernando Lalana", "Juvenil / Misterio", 1993],
  ["Muy personal", "Naim Darrechi", "Juvenil / Autobiografía", 2019],
  ["Los dos mundos de Zoé", "Ana García-Siñeriz", "Literatura Juvenil", 2011],
  ["Moby Dick", "Herman Melville", "Clásico de Aventuras", 1851],
  ["El señor del Cero", "María Isabel Molina", "Juvenil / Histórico", 1996],
  ["Ligar con príncipes", "Tyne O'Connell", "Juvenil / Romántica", 2006],
  ["El asesinato de la profesora de lengua", "Jordi Sierra i Fabra", "Literatura Juvenil", 1997],
  ["Bat Pat: El retorno del esqueleto", "Roberto Pavanello", "Infantil / Misterio", 2008],
  ["Manolito Gafotas", "Elvira Lindo", "Literatura Infantil / Humor", 1994],
  ["Robinson Crusoe", "Daniel Defoe", "Clásico de Aventuras", 1719],
  ["Sala de conflictos", "Jordi Sierra i Fabra", "Literatura Juvenil", 2001],
  ["El despertar de Cervantes", "Vicente Muñoz Puelles", "Novela Juvenil", 2016],
  ["¡Hola, Morris!", "Gabriela Keselman", "Literatura Infantil", 2011],
  ["Septimus: El anillo de las dos caras", "Angie Sage", "Fantasía Juvenil", 2011],
  ["La brújula dorada", "Philip Pullman", "Fantasía Juvenil", 1995],
  ["Tras la pista de la Salamandra", "Jean-Philippe Arrou-Vignod", "Juvenil / Misterio", 2003],
  ["Tiempo de misterios", "Manuel L. Alonso", "Juvenil / Misterio", 1995],
  ["El libro de los rostros", "Ana Alonso y Javier Pelegrín", "Juvenil / Thriller", 2018],

  /* ── 🧠 Clásicos, Teatro, Filosofía y Biografías ──────────────────── */
  ["Bodas de sangre / Yerma / La casa de Bernarda Alba", "Federico García Lorca", "Teatro Clásico", 1933],
  ["Mariposa Negra", "Fifi López Naranjo", "Poesía / Narrativa", 2010],
  ["Para ti, amor mío", "Fifi López Naranjo", "Poesía", 2012],
  ["Historia de una escalera", "Antonio Buero Vallejo", "Teatro Clásico", 1949],
  ["Ludwig van Beethoven", "Varios (Grandes Biografías)", "Biografía", null],
  ["Napoleón Bonaparte", "Varios (Grandes Biografías)", "Biografía", null],
  ["Miguel de Cervantes", "Varios (Grandes Biografías)", "Biografía", null],
  ["La vida privada de Tut-Ank-Amon", "Geneviève Tabouis", "Ensayo / Historia", 1929],
  ["Con una sonrisa, Ana Guerra", "Varios (Autobiográfico)", "Biografía Pop / Música", 2019],
  ["Shakespeare a la luz del arte sagrado", "Martin Lings", "Crítica Literaria / Ensayo", 1966],
  ["El primer antepasado del hombre", "Donald Johanson y Maitland Edey", "Divulgación Científica", 1981],
  ["Memorias de África", "Isak Dinesen (Karen Blixen)", "Autobiografía / Memorias", 1937],
  ["Los girasoles ciegos", "Alberto Méndez", "Ficción Histórica", 2004],
  ["Jesucristo y el juego del amor", "Anthony Burgess", "Novela Clásica", 1980],
  ["Egipto: Mitos y leyendas", "Lewis Spence", "Ensayo / Mitología", 1915],
  ["La medicina del alma", "Eric Rolf", "Autoayuda / Espiritualidad", 2005],
  ["Cuatro corazones con freno y marcha atrás", "Enrique Jardiel Poncela", "Teatro / Humor", 1936],
  ["La mascota agresiva", "Susan Price", "Guía / Divulgación", 1998],
  ["El libro de la salud infantil / El sueño", "Eduard Estivill y Montse Domènech", "Medicina / Cuidado Infantil", 1999],

  /* ── 🔮 Ficción Contemporánea, Erótica y Sobrenatural ─────────────── */
  ["Blonde", "Joyce Carol Oates", "Ficción Biográfica", 2000],
  ["Los Inmortales", "Michael Korda", "Ficción / Drama", 1992],
  ["El valle de los leones", "Ken Follett", "Thriller de Espionaje", 1986],
  ["Al otro lado del Estrecho", "Nicole Boumaâza", "Drama Social", 2002],
  ["Conexiones", "Elizabeth Stewart", "Thriller / Suspense", 2000],
  ["Holly", "Stephen King", "Thriller / Misterio", 2023],
  ["Buick 8, un coche perverso", "Stephen King", "Terror / Sobrenatural", 2002],
  ["Cincuenta sombras de Grey (I)", "E. L. James", "Novela Erótica", 2011],
  ["Cincuenta sombras liberadas (III)", "E. L. James", "Novela Erótica", 2012],
  ["Cincuenta sombras más oscuras (II)", "E. L. James", "Novela Erótica", 2012],
  ["Grey", "E. L. James", "Novela Erótica", 2015],
  ["El comité de la muerte", "Noah Gordon", "Drama Médico", 1969],
  ["La última confesión", "Morris West", "Novela Histórica / Drama", 2000],
  ["La pasión turca", "Antonio Gala", "Drama Romántico", 1993],
];
